app/base/models.py
# -*- encoding: utf-8 -*-


from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-

from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SelectField, TextAreaField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = StringField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = StringField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = StringField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

## Clients
class CreateClient(FlaskForm):
    nom    = StringField('nom', id='nom_client', validators=[DataRequired()])
    prenom = StringField('prenom', id='prenom_client', validators=[DataRequired()])

## Compte-rendu
class CreateData(FlaskForm):
    id_client = SelectField('id_client', id='id_client', validators=[DataRequired()])
    compte_rendu = TextAreaField('compte-rendu', id='compte_rendu', validators=[DataRequired()])
    id_collab = StringField('id_collab', id='id_collab', validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Connexion {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a target="_blank"
                                       href="">Voix CA</a> - Connexion
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Indentifiez-vous
                                    {% endif %}                                     
                                </p>    
                            </div>

                            <form method="post" action="" class="mt-4">
                                
                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">ET0</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1"><span class="fas fa-user-circle"></span></span>
                                        {{ form.username(placeholder="ET01234", class="form-control") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Mot de passe</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(placeholder="*********", class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                                            <label class="form-check-label" for="defaultCheck5">
                                              Se souvenir de moi
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <a href="{{ url_for('base_blueprint.register') }}" class="small text-right">S'inscrire</a>
                                        </div>
                                    </div>

                                </div>
                                <button type="submit" name="login" class="btn btn-block btn-primary">Connexion</button>
                            </form>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="font-weight-normal">
                                    &copy; CATS
                                    - coded by Usage BIG DATA
                                </span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Inscription {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} bg-soft {% endblock body_class %}

{% block content %}

    <main>

        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image" data-background="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    <a target="_blank">Voix CA</a> - Inscription
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Informations
                                    {% endif %}                                     
                                </p>    
                            </div>
                            
                            <form method="post" action="">
                            
                                {{ form.hidden_tag() }}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">ET0</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-user-shield"></span></span>
                                        {{ form.username(placeholder="ET01234", class="form-control") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Email</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                        {{ form.email(placeholder="marc.dupont@ca-ts.fr", class="input form-control", type="email") }}
                                    </div>  
                                </div>
                                <!-- End of Form -->

                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Mot de passe</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                            {{ form.password(placeholder="*******", class="form-control", type="password") }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->

                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="defaultCheck5">
                                            <label class="form-check-label" for="defaultCheck5">
                                              Accepter les conditions d'utilisation
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <a href="{{ url_for('base_blueprint.login') }}" class="small text-right">S'identifiez</a>
                                        </div>
                                    </div>
                                    
                                </div>
                                <button type="submit" name="register" class="btn btn-block btn-primary">S'inscrire</button>
                            </form>
                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="font-weight-normal">
                                    &copy; <a target="_blank">CATS</a>
                                    - coded by <a target="_blank" >Usage BIG DATA</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/footer.html
    <footer class="footer section py-5">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-6 mb-4 mb-lg-0">
                    <p class="mb-0 text-center text-xl-left">
                        &copy; <a class="text-primary font-weight-normal" target="_blank">CATS</a>
                        - coded by <a target="_blank">Usage BIG DATA</a>
                    </p>
                </div>

                <div class="col-12 col-lg-6">
                    <!-- List -->
                    <ul class="list-inline list-group-flush list-group-borderless text-center text-xl-right mb-0">
                        <li class="list-inline-item px-0 px-sm-2">
                            <a target="_blank">Voix CA</a>
                        </li>
                    </ul>
                    <!-- End List -->
                </div>
            </div>
        </div>
    </footer>

app/base/templates/includes/navigation.html
        <nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark pl-0 pr-2 pb-0">
            <div class="container-fluid px-0">
              <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                <div class="d-flex">

                </div>
                <!-- Navbar links -->
                <ul class="navbar-nav align-items-center">
                  <li class="nav-item dropdown">
                    <a class="nav-link pt-1 px-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <div class="media d-flex align-items-center">
                        <img class="user-avatar md-avatar rounded-circle" alt="Image placeholder" src="https://eu.ui-avatars.com/api/?name={{ current_user.username }}&background=random">
                        <div class="media-body ml-2 text-dark align-items-center d-none d-lg-block">
                          <span class="mb-0 font-small font-weight-bold">
                            {{ current_user.username }}
                          </span>
                        </div>
                      </div>
                    </a>
                    <div class="dropdown-menu dashboard-dropdown dropdown-menu-right mt-2">
                      <a class="dropdown-item font-weight-bold" href="/settings.html"><span class="fas fa-cog"></span>Paramètres</a>
                      <div role="separator" class="dropdown-divider"></div>
                      <a class="dropdown-item font-weight-bold" href="{{ url_for('base_blueprint.logout') }}">
                          <span class="fas fa-sign-out-alt text-danger"></span>Se déconnecter</a>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
        </nav>

app/base/templates/includes/scripts.html
    <!-- Core -->
    <script src="/static/assets/vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Vendor JS -->
    <script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>

    <!-- Slider -->
    <script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>

    <!-- Jarallax -->
    <script src="/static/assets/vendor/jarallax/dist/jarallax.min.js"></script>

    <!-- Smooth scroll -->
    <script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

    <!-- Count up -->
    <script src="/static/assets/vendor/countup.js/dist/countUp.umd.js"></script>

    <!-- Notyf -->
    <script src="/static/assets/vendor/notyf/notyf.min.js"></script>

    <!-- Charts -->
    <script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
    <script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

    <!-- Datepicker -->
    <script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

    <!-- Simplebar -->
    <script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <!-- Volt JS -->
    <script src="/static/assets/js/volt.min.js"></script>

    <!-- Jquery -->
    <script src="/static/assets/js/jquery-3.5.1.min.js"></script>

app/base/templates/includes/sidebar.html
    <nav id="sidebarMenu" class="sidebar d-md-block bg-primary text-white collapse px-4">
        <div class="sidebar-sticky pt-3 mx-auto">
            <div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
            <div class="d-flex align-items-center">
                <div class="user-avatar lg-avatar mr-4">
                <img src="/static/assets/img/team/profile-picture-3.jpg" class="card-img-top rounded-circle border-white" alt="Bonnie Green">
                </div>
                <div class="d-block">
                <h2 class="h6">
                    {{ current_user.username }}
                </h2>
                <a href="{{ url_for('base_blueprint.logout') }}" class="btn btn-secondary text-dark btn-xs">
                    <span class="mr-2"><span class="fas fa-sign-out-alt"></span></span>Se déconnecter</a>
                </div>
            </div>
            <div class="collapse-close d-md-none">
                <a href="#sidebarMenu" class="fas fa-times" data-toggle="collapse"
                    data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true"
                    aria-label="Toggle navigation"></a>
            </div>
            </div>
            <ul class="nav flex-column">
            <li class="nav-item  {% if 'dashboard' in segment %} active {% endif %}">
                <a href="/dashboard.html" class="nav-link">
                <span class="sidebar-icon"><span class="fas fa-chart-pie"></span></span>
                <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item  {% if 'clients' in segment %} active {% endif %}">
                <a href="/clients.html" class="nav-link">
                <span class="sidebar-icon"><span class="fas fa-users"></span></span>
                <span>Clients</span>
                </a>
            </li>
            <li class="nav-item  {% if 'mescomptesrendu' in segment %} active {% endif %}">
                <a href="/mescomptesrendu.html" class="nav-link">
                <span class="sidebar-icon"><span class="far fa-file-alt"></span></span>
                <span>Mes comptes-rendus</span>
                </a>
            </li>
            <li class="nav-item  {% if 'recherche' in segment %} active {% endif %}">
                <a href="/recherche.html" class="nav-link">
                <span class="sidebar-icon"><span class="fas fa-search"></span></span>
                <span>Recherche</span>
                </a>
            </li>


                 <li class="nav-item  {% if 'settings' in segment %} active {% endif %}">
                <a href="/settings.html" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-cog"></span></span>
                    <span>Paramètres</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('base_blueprint.logout') }}" class="nav-link">
                    <span class="sidebar-icon"><span class="fas fa-sign-out-alt text-danger"></span></span>
                    <span>Se déconnecter</span>
                </a>
            </li>
            </ul>
        </div>
    </nav>

app/base/templates/layouts/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">

<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- Primary Meta Tags -->
<title>
    Portail collaborateur VOIX-CA - {% block title %}{% endblock %}
</title>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Portail collaborateur VOIX-CA">
<meta name="author" content="Manon">



<!-- Favicon -->
<link rel="apple-touch-icon" sizes="120x120" href="/static/assets/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/static/assets/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/assets/img/favicon/favicon-16x16.png">
<link rel="manifest" href="/static/assets/img/favicon/site.webmanifest">
<link rel="mask-icon" href="/static/assets/img/favicon/safari-pinned-tab.svg" color="#ffffff">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- Fontawesome -->
<link type="text/css" href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">

<!-- Notyf -->
<link type="text/css" href="/static/assets/vendor/notyf/notyf.min.css" rel="stylesheet">

<!-- Volt CSS -->
<link type="text/css" href="/static/assets/css/volt.css" rel="stylesheet">

    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

</head> 
<body>
           
    {% block content %}{% endblock content %}

    {% include 'includes/scripts.html' %}    
    
    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

</body>
</html>

app/base/templates/layouts/base.html
<!DOCTYPE html>
<html lang="fr">

<head> 
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- Primary Meta Tags -->
<title>
   Portail collaborateur VOIX-CA - {% block title %}{% endblock %}
</title>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="title" content="Portail collaborateur VOIX-CA">
<meta name="author" content="Manon">


<!-- Favicon -->
<link rel="apple-touch-icon" sizes="120x120" href="/static/assets/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/static/assets/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/assets/img/favicon/favicon-16x16.png">
<link rel="manifest" href="/static/assets/img/favicon/site.webmanifest">
<link rel="mask-icon" href="/static/assets/img/favicon/safari-pinned-tab.svg" color="#ffffff">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<!-- Fontawesome -->
<link type="text/css" href="/static/assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">

<!-- Notyf -->
<link type="text/css" href="/static/assets/vendor/notyf/notyf.min.css" rel="stylesheet">

<!-- Volt CSS -->
<link type="text/css" href="/static/assets/css/volt.css" rel="stylesheet">

<!-- Datatable CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">
    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body>
    <nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-md-none">
        <a class="navbar-brand mr-lg-5" href="/">
            <img class="navbar-brand-dark" src="/static/assets/img/brand/light.svg" alt="Volt logo" /> <img class="navbar-brand-light" src="/static/assets/img/brand/dark.svg" alt="Volt logo" />
        </a>
        <div class="d-flex align-items-center">
            <button class="navbar-toggler d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>

    <div class="container-fluid bg-soft">
        <div class="row">
            <div class="col-12">

                {% include 'includes/sidebar.html' %}
            
                {% block content %}{% endblock content %}

            </div>
        </div>
    </div>
    {% include 'includes/scripts.html' %}    
    
    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}
    {% endblock javascripts %}

</body>
</html>